import pymysql
# from db_conn import open_conn

def regType0(str, cur):
    mydict = {
    'tipo_registro':str[0:1],
    'num_sequencia':str[1:13],
    'data_geracao_arquivo':str[13:21],
    'operadora':str[21:36].strip(),
    'uf_operadora':str[36:38],
    'codigo_cliente':str[38:53].strip(),
    'nome_cliente':str[53:93].strip(),
    'cgc_cliente':str[93:108].strip(),
    'id_conta_unica':str[123:129].strip(),
    'data_vencimento':str[133:141].strip(),
    'data_emissao':str[141:149].strip(),
    'filler':str[149:350],
    }
    sql = """INSERT INTO type_0 (
    tipo_registro,
    num_sequencia, 
    data_geracao_arquivo,
    operadora,
    uf_operadora,
    codigo_cliente,
    nome_cliente,
    cgc_cliente,
    id_conta_unica,
    data_vencimento,
    data_emissao
    ) 
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"""
    val = (
    mydict["tipo_registro"],
    mydict["num_sequencia"],
    mydict["data_geracao_arquivo"],
    mydict["operadora"],
    mydict["uf_operadora"],
    mydict["codigo_cliente"],
    mydict["nome_cliente"],
    mydict["cgc_cliente"],
    mydict["id_conta_unica"],
    mydict["data_vencimento"],
    mydict["data_emissao"]
    )
    cur.execute(sql, val)
    #return find_error

def regType1(str, cur):
    mydict = {
        'tipo_registro':str[0:1].strip(),
        'num_sequencia':str[1:13].strip(),
        'id_conta_unica':str[25:38].strip(),
        'data_vencimento':str[38:46].strip(),
        'data_emissao':str[46:54].strip(),
        'id_unico_recurso':str[54:79].strip(),
        'cnl_recurso':str[79:84].strip(),
        'nome_localidade':str[84:109].strip(),
        'ddd':str[109:111].strip(),
        'n_telefone':str[111:121].strip(),
        'tipo_servico':str[121:125].strip(),
        'desc_tipo_servico':str[125:160].strip(),
        'caracteristica_recurso':str[160:175].strip(),
        'degrau_recurso':str[175:177].strip(),
        'velocidade_recurso':str[177:182].strip(),
        'unidade_velocidade_recurso':str[182:186].strip(),
        'inicio_periodo_assinatura':str[186:194].strip(),
        'fim_periodo_assinatura':str[194:202].strip(),
        'inicio_periodo_servico':str[202:210].strip(),
        'fim_periodo_servico':str[210:218].strip(),
        'unidade_consumo':str[218:223].strip(),
        'quantidade_consumo':str[223:230].strip(),
        'sinal_valor_consumo':str[230:231].strip(),
        'valor_consumo':str[231:244].strip(),
        'sinal_assinatura':str[244:245].strip(),
        'valor_assinatura':str[245:258].strip(),
        'aliquota':str[258:260].strip(),
        'sinal_icms':str[260:261].strip(),
        'valor_icms':str[261:274].strip(),
        'sinal_total_outros_impostos':str[274:275].strip(),
        'valor_total_outros_impostos':str[275:288].strip(),
        'numero_nota_fiscal':str[288:300].strip(),
        'sinal_valor_conta':str[300:301].strip(),
        'valor_conta':str[301:314].strip()
        }
    sql = """INSERT INTO type_1 (
    tipo_registro,
    num_sequencia,
    id_conta_unica,
    data_vencimento,
    data_emissao,
    id_unico_recurso,
    cnl_recurso,
    nome_localidade,
    ddd,
    n_telefone,
    tipo_servico,
    desc_tipo_servico,
    caracteristica_recurso,
    degrau_recurso,
    velocidade_recurso,
    unidade_velocidade_recurso,
    inicio_periodo_assinatura,
    fim_periodo_assinatura,
    inicio_periodo_servico,
    fim_periodo_servico,
    unidade_consumo,
    quantidade_consumo,
    sinal_valor_consumo,
    valor_consumo,
    sinal_assinatura,
    valor_assinatura,
    aliquota,
    sinal_icms,
    valor_icms,
    sinal_total_outros_impostos,
    valor_total_outros_impostos,
    numero_nota_fiscal,
    sinal_valor_conta,
    valor_conta
    ) 
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"""
    val = (
        mydict["tipo_registro"],
        mydict["num_sequencia"],
        mydict["id_conta_unica"],
        mydict["data_vencimento"],
        mydict["data_emissao"],
        mydict["id_unico_recurso"],
        mydict["cnl_recurso"],
        mydict["nome_localidade"],
        mydict["ddd"],
        mydict["n_telefone"],
        mydict["tipo_servico"],
        mydict["desc_tipo_servico"],
        mydict["caracteristica_recurso"],
        mydict["degrau_recurso"],
        mydict["velocidade_recurso"],
        mydict["unidade_velocidade_recurso"],
        mydict["inicio_periodo_assinatura"],
        mydict["fim_periodo_assinatura"],
        mydict["inicio_periodo_servico"],
        mydict["fim_periodo_servico"],
        mydict["unidade_consumo"],
        mydict["quantidade_consumo"],
        mydict["sinal_valor_consumo"],
        mydict["valor_consumo"],
        mydict["sinal_assinatura"],
        mydict["valor_assinatura"],
        mydict["aliquota"],
        mydict["sinal_icms"],
        mydict["valor_icms"],
        mydict["sinal_total_outros_impostos"],
        mydict["valor_total_outros_impostos"],
        mydict["numero_nota_fiscal"],
        mydict["sinal_valor_conta"],
        mydict["valor_conta"]
        )
    cur.execute(sql, val)

def regType2(str, cur):
    mydict = {
    'tipo_registro':str[0:1],
    'num_sequencia':str[1:13],
    'data_geracao_arquivo':str[13:21],
    'operadora':str[21:36].strip(),
    'uf_operadora':str[36:38],
    'codigo_cliente':str[38:53].strip(),
    'nome_cliente':str[53:93].strip(),
    'cgc_cliente':str[93:108].strip(),
    'id_conta_unica':str[123:129].strip(),
    'data_vencimento':str[133:141].strip(),
    'data_emissao':str[141:149].strip(),
    'filler':str[149:350],
    }
    sql = """INSERT INTO type_2 (
    tipo_registro, 
    num_sequencia, 
    id_unico_recurso, 
    ddd, 
    numero_telefone, 
    caracteristica_recurso, 
    cnl_recurso_a, 
    localidade_a, 
    uf_a, 
    endereco_a, 
    numero_endereco_a, 
    complemento_a, 
    bairro_a, 
    cnl_recurso_b, 
    localidade_b, 
    uf_b, 
    endereco_b, 
    numero_endereco_b, 
    complemento_b, 
    bairro_b
    ) 
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"""
    val = (        
    mydict["tipo_registro"],
    mydict["num_sequencia"],
    mydict["id_unico_recurso"],
    mydict["ddd"],
    mydict["numero_telefone"],
    mydict["caracteristica_recurso"],
    mydict["cnl_recurso_a"],
    mydict["localidade_a"],
    mydict["uf_a"],
    mydict["endereco_a"],
    mydict["numero_endereco_a"],
    mydict["complemento_a"],
    mydict["bairro_a"],
    mydict["cnl_recurso_b"],
    mydict["localidade_b"],
    mydict["uf_b"],
    mydict["endereco_b"],
    mydict["numero_endereco_b"],
    mydict["complemento_b"],
    mydict["bairro_b"]
    )
    cur.execute(sql, val)

def regType3(str, cur):
    mydict = {
    'tipo_registro':str[0:1].strip(),
    'num_sequencia':str[1:13].strip(),
    'data_vencimento':str[13:21].strip(),
    'data_emissao':str[21:29].strip(),
    'identificador_unico_recurso':str[29:54].strip(),
    'cnl_recurso':str[54:59].strip(),
    'ddd':str[59:61].strip(),
    'numero_telefone':str[61:71].strip(),
    'caracteristica_recurso':str[71:86].strip(),
    'degrau_recurso':str[86:88].strip(),
    'data_ligacao':str[88:96].strip(),
    'cnl_localidade_chamada':str[96:101].strip(),
    'nome_localidade_chamada':str[101:126].strip(),
    'uf_telefone_chamado':str[126:128].strip(),
    'codigo_nacional_internacional':str[128:130].strip(),
    'codigo_operadora':str[130:132].strip(),
    'descricao_operadora':str[132:152].strip(),
    'codigo_pais_chamado':str[152:155].strip(),
    'area_ddd':str[155:159].strip(),
    'numero_telefone_chamado':str[159:169].strip(),
    'conjugado_numero_telefone_chamado':str[169:171].strip(),
    'duracao_ligacao':str[171:177].strip(),
    'categoria':str[177:180].strip(),
    'descricao_categoria':str[180:230].strip(),
    'horario_ligacao':str[230:236].strip(),
    'tipo_chamada':str[236:237].strip(),
    'grupo_horario_tarifario':str[237:238].strip(),
    'descricao_horario_tarifario':str[238:263].strip(),
    'degrau_ligacao':str[263:265].strip(),
    'sinal_valor_ligacao':str[265:266].strip(),
    'aliquota_icms':str[266:271].strip(),
    'valor_ligacao_com_imposto':str[271:284].strip(),
    'classe_servico':str[284:289].strip()
    }
    sql = """INSERT INTO type_3 (
    tipo_registro,
    num_sequencia,
    data_vencimento,
    data_emissao,
    identificador_unico_recurso,
    cnl_recurso,
    ddd,
    numero_telefone,
    caracteristica_recurso,
    degrau_recurso,
    data_ligacao,
    cnl_localidade_chamada,
    nome_localidade_chamada,
    uf_telefone_chamado,
    codigo_nacional_internacional,
    codigo_operadora,
    descricao_operadora,
    codigo_pais_chamado,
    area_ddd,
    numero_telefone_chamado,
    conjugado_numero_telefone_chamado,
    duracao_ligacao,
    categoria,
    descricao_categoria,
    horario_ligacao,
    tipo_chamada,
    grupo_horario_tarifario,
    descricao_horario_tarifario,
    degrau_ligacao,
    sinal_valor_ligacao,
    aliquota_icms,
    valor_ligacao_com_imposto,
    classe_servico
    )

    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"""
    val = (
    mydict["tipo_registro"],
    mydict["num_sequencia"],
    mydict["data_vencimento"],
    mydict["data_emissao"],
    mydict["identificador_unico_recurso"],
    mydict["cnl_recurso"],
    mydict["ddd"],
    mydict["numero_telefone"],
    mydict["caracteristica_recurso"],
    mydict["degrau_recurso"],
    mydict["data_ligacao"],
    mydict["cnl_localidade_chamada"],
    mydict["nome_localidade_chamada"],
    mydict["uf_telefone_chamado"],
    mydict["codigo_nacional_internacional"],
    mydict["codigo_operadora"],
    mydict["descricao_operadora"],
    mydict["codigo_pais_chamado"],
    mydict["area_ddd"],
    mydict["numero_telefone_chamado"],
    mydict["conjugado_numero_telefone_chamado"],
    mydict["duracao_ligacao"],
    mydict["categoria"],
    mydict["descricao_categoria"],
    mydict["horario_ligacao"],
    mydict["tipo_chamada"],
    mydict["grupo_horario_tarifario"],
    mydict["descricao_horario_tarifario"],
    mydict["degrau_ligacao"],
    mydict["sinal_valor_ligacao"],
    mydict["aliquota_icms"],
    mydict["valor_ligacao_com_imposto"],
    mydict["classe_servico"]
    )
    cur.execute(sql,val)

def regType4(str, cur):
    mydict = {
    'tipo_registro':str[0:1].strip(),
    'num_sequencia':str[1:13].strip(),
    'data_vencimento':str[13:21].strip(),
    'data_emissao':str[21:29].strip(),
    'identificador_unico_recurso':str[29:54].strip(),
    'cnl_recurso':str[54:59].strip(),
    'ddd':str[59:61].strip(),
    'numero_telefone':str[61:71].strip(),
    'caracteristica_recurso':str[71:86].strip(),
    'data_servico':str[86:94].strip(),
    'cnl_localidade_chamada':str[94:99].strip(),
    'nome_localidade_chamada':str[99:124].strip(),
    'uf_telefone_chamado':str[124:126].strip(),
    'codigo_nacional_internacional':str[126:128].strip(),
    'codigo_operadora':str[128:130].strip(),
    'descricao_operadora':str[130:150].strip(),
    'codigo_pais_chamado':str[150:153].strip(),
    'area_ddd':str[153:157].strip(),
    'numero_telefone_chamado':str[157:167].strip(),
    'conjugado_numero_telefone_chamado':str[167:169].strip(),
    'duracao_ligacao':str[169:175].strip(),
    'horario_ligacao':str[175:181].strip(),
    'grupo_categoria':str[181:184].strip(),
    'descricao_grupo_categoria':str[184:214].strip(),
    'categoria':str[214:217].strip(),
    'descricao_categoria':str[217:257].strip(),
    'sinal_valor_ligacao':str[257:258].strip(),
    'valor_ligacao':str[258:271].strip(),
    'classe_servico':str[271:276].strip(),
    'filler':str[276:350].strip()
    }
    sql = """INSERT INTO type_4 (
    tipo_registro,
    num_sequencia,
    data_vencimento,
    data_emissao,
    identificador_unico_recurso,
    cnl_recurso,
    ddd,
    numero_telefone,
    caracteristica_recurso,
    data_servico,
    cnl_localidade_chamada,
    nome_localidade_chamada,
    uf_telefone_chamado,
    codigo_nacional_internacional,
    codigo_operadora,
    descricao_operadora,
    codigo_pais_chamado,
    area_ddd,
    numero_telefone_chamado,
    conjugado_numero_telefone_chamado,
    duracao_ligacao,
    horario_ligacao,
    grupo_categoria,
    descricao_grupo_categoria,
    categoria,
    descricao_categoria,
    sinal_valor_ligacao,
    valor_ligacao,
    classe_servico
    )

    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"""
    val = (
    mydict["tipo_registro"],
    mydict["num_sequencia"],
    mydict["data_vencimento"],
    mydict["data_emissao"],
    mydict["identificador_unico_recurso"],
    mydict["cnl_recurso"],
    mydict["ddd"],
    mydict["numero_telefone"],
    mydict["caracteristica_recurso"],
    mydict["data_servico"],
    mydict["cnl_localidade_chamada"],
    mydict["nome_localidade_chamada"],
    mydict["uf_telefone_chamado"],
    mydict["codigo_nacional_internacional"],
    mydict["codigo_operadora"],
    mydict["descricao_operadora"],
    mydict["codigo_pais_chamado"],
    mydict["area_ddd"],
    mydict["numero_telefone_chamado"],
    mydict["conjugado_numero_telefone_chamado"],
    mydict["duracao_ligacao"],
    mydict["horario_ligacao"],
    mydict["grupo_categoria"],
    mydict["descricao_grupo_categoria"],
    mydict["categoria"],
    mydict["descricao_categoria"],
    mydict["sinal_valor_ligacao"],
    mydict["valor_ligacao"],
    mydict["classe_servico"]
    )
    cur.execute(sql, val)
#return find_error

# Type5
def regType5(str, cur):
    mydict = {
    'tipo_registro':str[0:1].strip(),
    'num_sequencia':str[1:13].strip(),
    'data_vencimento':str[13:21].strip(),
    'data_emissao':str[21:29].strip(),
    'identificador_unico_recurso':str[29:54].strip(),
    'identificador_conta_unica':str[54:79].strip(),
    'cnl_recurso':str[79:84].strip(),
    'ddd':str[84:86].strip(),
    'numero_telefone':str[86:96].strip(),
    'grupo_categoria':str[96:99].strip(),
    'descricao_grupo_categoria':str[99:179].strip(),
    'sinal_valor_ligacao':str[179:180].strip(),
    'base_calculo_desconto':str[180:193].strip(),
    'percentual_desconto':str[193:198].strip(),
    'valor_ligacao':str[198:211].strip(),
    'data_inicio_acerto':str[211:219].strip(),
    'hora_inicio_acerto':str[219:225].strip(),
    'data_fim_acerto':str[225:233].strip(),
    'hora_fim_acerto':str[233:239].strip(),
    'classe_servico':str[239:244].strip()
    }
    sql = """INSERT INTO type_5 (
    tipo_registro,
    num_sequencia,
    data_vencimento,
    data_emissao,
    identificador_unico_recurso,
    identificador_conta_unica,
    cnl_recurso,
    ddd,
    numero_telefone,
    grupo_categoria,
    descricao_grupo_categoria,
    sinal_valor_ligacao,
    base_calculo_desconto,
    percentual_desconto,
    valor_ligacao,
    data_inicio_acerto,
    hora_inicio_acerto,
    data_fim_acerto,
    hora_fim_acerto,
    classe_servico
    )

    VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"""
    val = (
    mydict["tipo_registro"],
    mydict["num_sequencia"],
    mydict["data_vencimento"],
    mydict["data_emissao"],
    mydict["identificador_unico_recurso"],
    mydict["identificador_conta_unica"],
    mydict["cnl_recurso"],
    mydict["ddd"],
    mydict["numero_telefone"],
    mydict["grupo_categoria"],
    mydict["descricao_grupo_categoria"],
    mydict["sinal_valor_ligacao"],
    mydict["base_calculo_desconto"],
    mydict["percentual_desconto"],
    mydict["valor_ligacao"],
    mydict["data_inicio_acerto"],
    mydict["hora_inicio_acerto"],
    mydict["data_fim_acerto"],
    mydict["hora_fim_acerto"],
    mydict["classe_servico"]
    )
    cur.execute(sql, val)

# Type9
def regType9(str, cur):
    mydict = {            
    'tipo_registro':str[0:1],
    'num_sequencia':str[1:13],
    'codigo_cliente':str[13:28],
    'identificacao_conta_unica':str[28:53],
    'data_vencimento':str[53:61],
    'data_emissao':str[61:69],
    'quantidade_registros':str[69:81],
    'quantidade_linhas':str[81:93],
    'sinal_total':str[93:94],
    'valor_total':str[94:107],
    'filler':str[107:350]
    }
    sql = """INSERT INTO type_9 (
    tipo_registro,
    num_sequencia,
    codigo_cliente,
    identificacao_conta_unica,
    data_vencimento,
    data_emissao,
    quantidade_registros,
    quantidade_linhas,
    sinal_total,
    valor_total
    )

    VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"""
    val = (
    mydict["tipo_registro"],
    mydict["num_sequencia"],
    mydict["codigo_cliente"],
    mydict["identificacao_conta_unica"],
    mydict["data_vencimento"],
    mydict["data_emissao"],
    mydict["quantidade_registros"],
    mydict["quantidade_linhas"],
    mydict["sinal_total"],
    mydict["valor_total"]
    )
    cur.execute(sql, val)